### ISSUE TITLE
Run_digits not working

### ISSUE THREAD

**Issue by francescobodria** [BeenKim/MMD-critic#13]
I tried your example in run digits but It doesn't work.
The error is this:
Traceback (most recent call last):
  File "run_digits.py", line 223, in <module>
    main(data_prefix, output_prefix, gamma, m, alltestm, kernel_type, do_output_pics)
  File "run_digits.py", line 187, in main
    os.path.join(data_prefix, 'usps.t'))
  File "run_digits.py", line 116, in run
    plotfigs2(digitsdat.X[selected[sortedindx], :], selectedy[sortedindx], outfig)
  File "run_digits.py", line 67, in plotfigs2
    ax = fig.add_subplot(gs[i - begin_at])
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/figure.py", line 1419, in add_subplot
    a = subplot_class_factory(projection_class)(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axes/_subplots.py", line 73, in __init__
    self.update_params()
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axes/_subplots.py", line 133, in update_params
    return_all=True)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/gridspec.py", line 592, in get_position
    rows, cols = np.unravel_index([self.num1, self.num2], (nrows, ncols))
  File "<__array_function__ internals>", line 6, in unravel_index
TypeError: 'float' object cannot be interpreted as an integer

I fixed the problem by modifying the run_digits.py in line 54 by added int before the nrows and ncolumns  arguments of GridSpec:
gs = gridspec.GridSpec(int(int(perpic_m/perrow)+offset/perrow), int(perrow), wspace=0.0, hspace=0.0)

Hope this is useful for someone.

**Comment by anhtrangle** [comment]
@francescobodria Yes it's really helpful! Thanks a lot for ur post! 

> I tried your example in run digits but It doesn't work.
> The error is this:
> Traceback (most recent call last):
> File "run_digits.py", line 223, in
> main(data_prefix, output_prefix, gamma, m, alltestm, kernel_type, do_output_pics)
> File "run_digits.py", line 187, in main
> os.path.join(data_prefix, 'usps.t'))
> File "run_digits.py", line 116, in run
> plotfigs2(digitsdat.X[selected[sortedindx], :], selectedy[sortedindx], outfig)
> File "run_digits.py", line 67, in plotfigs2
> ax = fig.add_subplot(gs[i - begin_at])
> File "/usr/local/lib/python3.6/dist-packages/matplotlib/figure.py", line 1419, in add_subplot
> a = subplot_class_factory(projection_class)(self, *args, **kwargs)
> File "/usr/local/lib/python3.6/dist-packages/matplotlib/axes/_subplots.py", line 73, in **init**
> self.update_params()
> File "/usr/local/lib/python3.6/dist-packages/matplotlib/axes/_subplots.py", line 133, in update_params
> return_all=True)
> File "/usr/local/lib/python3.6/dist-packages/matplotlib/gridspec.py", line 592, in get_position
> rows, cols = np.unravel_index([self.num1, self.num2], (nrows, ncols))
> File "<**array_function** internals>", line 6, in unravel_index
> TypeError: 'float' object cannot be interpreted as an integer
> 
> I fixed the problem by modifying the run_digits.py in line 54 by added int before the nrows and ncolumns arguments of GridSpec:
> gs = gridspec.GridSpec(int(int(perpic_m/perrow)+offset/perrow), int(perrow), wspace=0.0, hspace=0.0)
> 
> Hope this is useful for someone.
